cluster:
  - name: "k3s-cluster"
    type: "k3s"
    description: "K3s Kubernetes Cluster"
    node_common_config: "k3s.base.yaml"
    inventory:
      controller:
        - k3s-main-01: "nodes/k3s-main-01.yaml"
      worker:
        - k3s-worker-01: "nodes/k3s-worker-01.yaml"
        - k3s-worker-02: "nodes/k3s-worker-02.yaml"
